// Generated by CoffeeScript 1.4.0
(function() {

  define(function(require, exports) {
    exports.list = ['official', 'guide', 'sites', 'modules', 'blog', 'realtime', 'functional', 'libuv', 'graphics', 'resources', 'languages'];
  });

}).call(this);
