// Generated by CoffeeScript 1.4.0
(function() {

  define(function(require, exports) {
    var delay, render, show, wrap;
    show = require('./tool').show;
    delay = function(t, f) {
      return setTimeout(f, t);
    };
    wrap = function(name) {
      return "../docs/" + name + ".docs";
    };
    render = function(data) {
      var lines, text;
      lines = data.split('\n');
      lines = lines.map(function(line) {
        return line.replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/\s/g, '&nbsp;').replace(/(https?:\S+)/g, '<a href="$1">$1</a>');
      });
      text = lines.join('<br>');
      return $('#byobu').insertAdjacentHTML('beforeend', "<div class='card'>" + text + "</div>");
    };
    exports.load = function(name, cb) {
      var req;
      if ((name != null) && (name.length != null) && (name.length > 0)) {
        req = new XMLHttpRequest;
        req.open('get', wrap(name));
        req.send();
        return req.onload = function(data) {
          var w, width;
          data = data.target.response;
          render(data);
          w = $('#byobu').clientWidth;
          width = w + 700;
          $('#byobu').style.width = "" + width + "px";
          if (cb != null) {
            return delay(0, cb);
          }
        };
      }
    };
  });

}).call(this);
