// Generated by CoffeeScript 1.4.0
(function() {

  define(function(require, exports) {
    var byobu, list, load, render, show, win;
    window.$ = function(str) {
      return document.querySelector(str);
    };
    byobu = $('#byobu');
    show = require('./tool').show;
    load = require('./fetch').load;
    list = require('./describe').list;
    show(list);
    require('./slide');
    win = {
      w: document.width,
      h: document.height
    };
    byobu.style.width = 0;
    byobu.style.paddingRight = win.w - 700;
    (render = function() {
      load(list.shift(), render);
      return show('width', byobu.style.width, list);
    })();
  });

}).call(this);
