// Generated by CoffeeScript 1.4.0
(function() {
  var __slice = [].slice;

  define(function(require, exports) {
    exports.show = function() {
      var args;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      return console.log.apply(console, args);
    };
  });

}).call(this);
